apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-registry-sync-operator
  labels:
    app: istio-registry-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-registry-sync
  template:
    metadata:
      labels:
        app: istio-registry-sync
    spec:
      serviceAccountName: istio-registry-sync-service-account
      containers:
      - name: istio-registry-sync-server
        image: docker.cloudsmith.io/tetrate/tis-containers:v0.5.0
        imagePullPolicy: Always
        args:
        - serve
        env:
        - name: PUBLISH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: aws-region
              name: aws-config
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access-key-id
              name: aws-creds
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret-access-key
              name: aws-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-registry-sync-service-account
  labels:
    app: istio-registry-sync
