apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-registry-sync-operator
  labels:
    app: istio-registry-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-registry-sync
  template:
    metadata:
      labels:
        app: istio-registry-sync
    spec:
      serviceAccountName: istio-registry-sync-service-account
      containers:
      - name: istio-registry-sync-server
        image: ghcr.io/tetratelabs/istio-registry-sync:v0.3
        imagePullPolicy: Always
        args:
        - serve
        env:
        - name: PUBLISH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: aws-region
              name: aws-config
