apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-registry-sync-service-entry-role
  labels:
    app: istio-registry-sync
rules:
# ServiceEntries
- apiGroups: ["networking.istio.io"]
  resources: ["serviceentries"]
  verbs: ["create", "get", "list", "watch", "patch", "delete", "update"]
# We create a service at startup to host our metrics endpoint
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-registry-sync-service-entry-rolebinding
  labels:
    app: istio-registry-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-registry-sync-service-entry-role
subjects:
  - kind: ServiceAccount
    name: istio-registry-sync-service-account
    namespace: default
